### PR TITLE
Adding medieval to web configurator

### PR DESCRIPTION
**Pull request by waltercool**
Medieval bagpipe fingerings looks great to me, same as I had locally... as far I can test.

### CODE REVIEW

**Comment by waltercool** [comment]
Now, despise my configuration being at Amol, the website automatically selects  Key-D. I need to manually change to Key-C to work fine.

**Comment by waltercool** [comment]
Added a hotfix to default C for medieval bagpipes.

**Comment by waltercool** [comment]
Hmm been reviewing some stuff which doesn't make much sense

Let me work a bit on it and let me know
Screenshot_20231206_005650

**Comment by waltercool** [comment]
OK, I think it's mostly fine, adding the last c here is unnecessary and not every medieval bagpipe uses it.

It's just weird for me to have h for ox?????? and a for oo?????? but it's fine (o = open, x = pressed, ? = open/close) but not bad actually.

This is from one of my bagpipes Amol by the way
Screenshot_20231206_014659

And this is from the Fagerström Medieval
Screenshot_20231206_014921

**Comment by waltercool** [comment]
Enabled G4 by default for Medieval.

**Comment by amowry** [comment]
Thanks Walter-- the reason the medieval pipes aren't in the current version of the Config Tool html is that they are added dynamically by the JavaScript if it detects that your firmware version is 2.2 or higher. So, I think the current version that's on the web server should be working correctly with medieval pipes, but let me know if it's not. I'm happy to add any additional changes to the fingering. As far as I know you're still the only one using it because I haven't released the firmware, and no one else has mentioned it.

**Comment by waltercool** [comment]
Oh, I can see that from warbl.xyz, it works fantastic. I can see the html doesn't have medieval, but it dynamically adds medieval and Barbaro. So there is something wrong for me.

If I try "your website", configure.html from warbl.xyz, I get a "WARB firmware version: 2.2 Your firmware is up to date" and everything works fine.

If I try this from "my website" using latest master, I get a WARBL firmware version: 2.2 There is a firmware update available".

Is there something I need to be aware of?

**Comment by waltercool** [comment]
Aha, quick update. I see there are differences between warbl.xyz configuration html and master html.

**Pull request closed without merging**
